language: python

python:
  - "3.6"

install:
  - pip install --editable . # Install it self
  - pip install -r requirements-test.txt # Install test dependencies
  - pip install codecov # Install coveralls

before_script:
  - python ./bin/py/run_test_webapp.py
  - sleep 10

script:
  - pytest tests --cov=crawlib # Run unittest

notifications:
  email: false # Mute email notification

after_success:
  - codecov # travis-ci will transfer data to codecov after success
