version: 2
jobs:
  test_crawlib:
    docker:
      - image: circleci/python:3.6.8-stretch-browsers
      - image: circleci/mongo:3.6
        environment:
          MONGO_INITDB_ROOT_USERNAME: username
          MONGO_INITDB_ROOT_PASSWORD: password
      - image: circleci/postgres:10.6-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
    context:
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
            make up
            make pip-dev-install
            make req-dev
            make req-test
          no_output_timeout: "60s"
      # in circleci runtime, we use circleci/mongo:3.6 docker image
      # there's no need to call make run-mongo to use the official mongo:3.6 image
      - run:
          command: |
            make run-test-webapp
          background: true
      - run:
          command: |
            make cov-only

workflows:
  version: 2
  test_workflow:
    jobs:
      - test_crawlib
